/******** INSERTS ***************************************************************************************************************************************/

INSERT INTO APLICACOES_FATPROD(OPERACAOID, FATORPRODID, quantidade, UNIDADEMEDIDA) VALUES (?, ?, ?, ?);
INSERT INTO ARMAZENS(QUINTAID, EDIFICIOID, nome, area, UNIDADEMEDIDA) VALUES (?, ?, ?, ?, ?);
INSERT INTO CICLOS(nomeCiclo, ESPECIEVEGETALID, inicio, fim, UNIDADEMEDIDAID) VALUES (?, ?, ?, ?, ?);
INSERT INTO COLHEITAS(OPERACAOID, quantidade, UNIDADEMEDIDA) VALUES (?, ?, ?);
INSERT INTO COMPONENTES(FICHATECNICAID, idxComponente, SUBSTANCIAID) VALUES (?, ?, ?);
INSERT INTO CULTIVOS(QUINTAID, PARCELAID, CULTURAID, dataInicio, dataFim, quantidade, UNIDADEMEDIDA, SETORREGAID) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO CULTURAS(idCultura, TIPOCULTURAID, ESPECIEVEGETALID, nome, nomeCompleto) VALUES (?, ?, ?, ?, ?);
INSERT INTO EDIFICIOS(QUINTAID, idEdificio) VALUES (?, ?);
INSERT INTO ESPECIES_VEGETAIS(idEspecieVegetal, especie, nomeComum) VALUES (?, ?, ?);
INSERT INTO FATORES_PRODUCAO(idFatorProducao, fabricante, FORMULACAOID, FICHATECNICAID) VALUES (?, ?, ?, ?);
INSERT INTO FERTIRREGAS(OPERACAOID, quantidade, UNIDADEMEDIDA, SETOR, RECEITAID) VALUES (?, ?, ?, ?, ?);
INSERT INTO FICHAS_TECNICAS(idFichaTecnica) VALUES (?);
INSERT INTO FORMULACOES(idFormulacao, formato, tipo, aplicacao) VALUES (?, ?, ?, ?);
INSERT INTO GARAGENS(QUINTAID, EDIFICIOID, nome, area, UNIDADEMEDIDA) VALUES (?, ?, ?, ?, ?);
INSERT INTO INCORPS_SOLO(OPERACAOID, quantidade, UNIDADEMEDIDA) VALUES (?, ?, ?);
INSERT INTO MIX(idReceita) VALUES (?);
INSERT INTO MOBILIZACOES_SOLO(OPERACAOID, quantidade, UNIDADEMEDIDA) VALUES (?, ?, ?);
INSERT INTO MOINHOS(QUINTAID, EDIFICIOID, nome, area, UNIDADEMEDIDA) VALUES (?, ?, ?, ?, ?);
INSERT INTO MONDAS(OPERACAOID, quantidade, UNIDADEMEDIDA) VALUES (?, ?, ?);
INSERT INTO OPERACOES(idOperacao, QUINTAID, PARCELAID, CULTURAID, OPERADORID, dataInicio, dataFim, dataInicioCultivo, timestamp, anulado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO OPERACOES_LOGS(idLog, OPERACAOID, timestamp, descricao) VALUES (?, ?, ?, ?);
INSERT INTO OPERADORES(idOperador, nome) VALUES (?, ?);
INSERT INTO PARCELAS(QUINTAID, idParcela, nome, area, UNIDADEMEDIDA) VALUES (?, ?, ?, ?, ?);
INSERT INTO PLANTACOES(OPERACAOID, quantidade, UNIDADEMEDIDA) VALUES (?, ?, ?);
INSERT INTO PODAS(OPERACAOID, quantidade, UNIDADEMEDIDA) VALUES (?, ?, ?);
INSERT INTO PRODUTOS(CULTURAID, produto, quantidade, UNIDADEMEDIDA, TIPOCONSUMOID) VALUES (?, ?, ?, ?, ?);
INSERT INTO QUINTAS(idQuinta, nome) VALUES (?, ?);
INSERT INTO RECEITAS(RECEITAID, FATORPRODID, quantidadePorHectar, UNIDADEMEDIDA) VALUES (?, ?, ?, ?);
INSERT INTO REGAS(OPERACAOID, quantidade, UNIDADEMEDIDA, SETOR) VALUES (?, ?, ?, ?);
INSERT INTO SEMENTEIRAS(OPERACAOID, quantidade, UNIDADEMEDIDA) VALUES (?, ?, ?);
INSERT INTO SETORES_REGA(idSetor, QUINTAID, EDIFICIOID, dataInicio, dataFim, caudalMaximo, UNIDADEMEDIDA) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO SISTEMAS_REGA(QUINTAID, EDIFICIOID, nome, area, UNIDADEMEDIDA) VALUES (?, ?, ?, ?, ?);
INSERT INTO SUBSTANCIAS(idSubstancia, substancia, percentagem, UNIDADEMEDIDA) VALUES (?, ?, ?, ?);
INSERT INTO TIPOS_CONSUMO(idTipoConsumo, nome) VALUES (?, ?);
INSERT INTO TIPOS_CULTURA(idTipoCultura, nome) VALUES (?, ?);
INSERT INTO UNIDADES_MEDIDA(idUnidadeMedida, nomeCompleto) VALUES (?, ?);



/******** UPDATES ***************************************************************************************************************************************/

UPDATE APLICACOES_FATPROD SET FATORPRODID = ?, quantidade = ?, UNIDADEMEDIDA = ? WHERE OPERACAOID = ?;
UPDATE ARMAZENS SET nome = ?, area = ?, UNIDADEMEDIDA = ? WHERE QUINTAID = ? AND EDIFICIOID = ?;
UPDATE CICLOS SET inicio = ?, fim = ?, UNIDADEMEDIDAID = ? WHERE nomeCiclo = ? AND ESPECIEVEGETALID = ?;
UPDATE COLHEITAS SET quantidade = ?, UNIDADEMEDIDA = ? WHERE OPERACAOID = ?;
UPDATE COMPONENTES SET  WHERE FICHATECNICAID = ? AND idxComponente = ? AND SUBSTANCIAID = ?;
UPDATE CULTIVOS SET QUINTAID = ?, dataFim = ?, quantidade = ?, UNIDADEMEDIDA = ?, SETORREGAID = ? WHERE PARCELAID = ? AND CULTURAID = ? AND dataInicio = ?;
UPDATE CULTURAS SET TIPOCULTURAID = ?, ESPECIEVEGETALID = ?, nome = ?, nomeCompleto = ? WHERE idCultura = ?;
UPDATE EDIFICIOS SET  WHERE QUINTAID = ? AND idEdificio = ?;
UPDATE ESPECIES_VEGETAIS SET especie = ?, nomeComum = ? WHERE idEspecieVegetal = ?;
UPDATE FATORES_PRODUCAO SET fabricante = ?, FORMULACAOID = ?, FICHATECNICAID = ? WHERE idFatorProducao = ?;
UPDATE FERTIRREGAS SET quantidade = ?, UNIDADEMEDIDA = ?, SETOR = ?, RECEITAID = ? WHERE OPERACAOID = ?;
UPDATE FICHAS_TECNICAS SET  WHERE idFichaTecnica = ?;
UPDATE FORMULACOES SET formato = ?, tipo = ?, aplicacao = ? WHERE idFormulacao = ?;
UPDATE GARAGENS SET nome = ?, area = ?, UNIDADEMEDIDA = ? WHERE QUINTAID = ? AND EDIFICIOID = ?;
UPDATE INCORPS_SOLO SET quantidade = ?, UNIDADEMEDIDA = ? WHERE OPERACAOID = ?;
UPDATE MIX SET  WHERE idReceita = ?;
UPDATE MOBILIZACOES_SOLO SET quantidade = ?, UNIDADEMEDIDA = ? WHERE OPERACAOID = ?;
UPDATE MOINHOS SET nome = ?, area = ?, UNIDADEMEDIDA = ? WHERE QUINTAID = ? AND EDIFICIOID = ?;
UPDATE MONDAS SET quantidade = ?, UNIDADEMEDIDA = ? WHERE OPERACAOID = ?;
UPDATE OPERACOES SET QUINTAID = ?, PARCELAID = ?, CULTURAID = ?, OPERADORID = ?, dataInicio = ?, dataFim = ?, dataInicioCultivo = ?, timestamp = ?, anulado = ? WHERE idOperacao = ?;
UPDATE OPERACOES_LOGS SET OPERACAOID = ?, timestamp = ?, descricao = ? WHERE idLog = ?;
UPDATE OPERADORES SET nome = ? WHERE idOperador = ?;
UPDATE PARCELAS SET nome = ?, area = ?, UNIDADEMEDIDA = ? WHERE QUINTAID = ? AND idParcela = ?;
UPDATE PLANTACOES SET quantidade = ?, UNIDADEMEDIDA = ? WHERE OPERACAOID = ?;
UPDATE PODAS SET quantidade = ?, UNIDADEMEDIDA = ? WHERE OPERACAOID = ?;
UPDATE PRODUTOS SET quantidade = ?, UNIDADEMEDIDA = ?, TIPOCONSUMOID = ? WHERE CULTURAID = ? AND produto = ?;
UPDATE QUINTAS SET nome = ? WHERE idQuinta = ?;
UPDATE RECEITAS SET quantidadePorHectar = ?, UNIDADEMEDIDA = ? WHERE RECEITAID = ? AND FATORPRODID = ?;
UPDATE REGAS SET quantidade = ?, UNIDADEMEDIDA = ?, SETOR = ? WHERE OPERACAOID = ?;
UPDATE SEMENTEIRAS SET quantidade = ?, UNIDADEMEDIDA = ? WHERE OPERACAOID = ?;
UPDATE SETORES_REGA SET QUINTAID = ?, EDIFICIOID = ?, dataInicio = ?, dataFim = ?, caudalMaximo = ?, UNIDADEMEDIDA = ? WHERE idSetor = ?;
UPDATE SISTEMAS_REGA SET nome = ?, area = ?, UNIDADEMEDIDA = ? WHERE QUINTAID = ? AND EDIFICIOID = ?;
UPDATE SUBSTANCIAS SET substancia = ?, percentagem = ?, UNIDADEMEDIDA = ? WHERE idSubstancia = ?;
UPDATE TIPOS_CONSUMO SET nome = ? WHERE idTipoConsumo = ?;
UPDATE TIPOS_CULTURA SET nome = ? WHERE idTipoCultura = ?;
UPDATE UNIDADES_MEDIDA SET nomeCompleto = ? WHERE idUnidadeMedida = ?;



/******** DELETES ***************************************************************************************************************************************/

DELETE FROM APLICACOES_FATPROD WHERE OPERACAOID = ?;
DELETE FROM ARMAZENS WHERE QUINTAID = ? AND EDIFICIOID = ?;
DELETE FROM CICLOS WHERE nomeCiclo = ? AND ESPECIEVEGETALID = ?;
DELETE FROM COLHEITAS WHERE OPERACAOID = ?;
DELETE FROM COMPONENTES WHERE FICHATECNICAID = ? AND idxComponente = ? AND SUBSTANCIAID = ?;
DELETE FROM CULTIVOS WHERE PARCELAID = ? AND CULTURAID = ? AND dataInicio = ?;
DELETE FROM CULTURAS WHERE idCultura = ?;
DELETE FROM EDIFICIOS WHERE QUINTAID = ? AND idEdificio = ?;
DELETE FROM ESPECIES_VEGETAIS WHERE idEspecieVegetal = ?;
DELETE FROM FATORES_PRODUCAO WHERE idFatorProducao = ?;
DELETE FROM FERTIRREGAS WHERE OPERACAOID = ?;
DELETE FROM FICHAS_TECNICAS WHERE idFichaTecnica = ?;
DELETE FROM FORMULACOES WHERE idFormulacao = ?;
DELETE FROM GARAGENS WHERE QUINTAID = ? AND EDIFICIOID = ?;
DELETE FROM INCORPS_SOLO WHERE OPERACAOID = ?;
DELETE FROM MIX WHERE idReceita = ?;
DELETE FROM MOBILIZACOES_SOLO WHERE OPERACAOID = ?;
DELETE FROM MOINHOS WHERE QUINTAID = ? AND EDIFICIOID = ?;
DELETE FROM MONDAS WHERE OPERACAOID = ?;
DELETE FROM OPERACOES WHERE idOperacao = ?;
DELETE FROM OPERACOES_LOGS WHERE idLog = ?;
DELETE FROM OPERADORES WHERE idOperador = ?;
DELETE FROM PARCELAS WHERE QUINTAID = ? AND idParcela = ?;
DELETE FROM PLANTACOES WHERE OPERACAOID = ?;
DELETE FROM PODAS WHERE OPERACAOID = ?;
DELETE FROM PRODUTOS WHERE CULTURAID = ? AND produto = ?;
DELETE FROM QUINTAS WHERE idQuinta = ?;
DELETE FROM RECEITAS WHERE RECEITAID = ? AND FATORPRODID = ? AND quantidadePorHectar = ?;
DELETE FROM REGAS WHERE OPERACAOID = ?;
DELETE FROM SEMENTEIRAS WHERE OPERACAOID = ?;
DELETE FROM SETORES_REGA WHERE idSetor = ?;
DELETE FROM SISTEMAS_REGA WHERE QUINTAID = ? AND EDIFICIOID = ?;
DELETE FROM SUBSTANCIAS WHERE idSubstancia = ?;
DELETE FROM TIPOS_CONSUMO WHERE idTipoConsumo = ?;
DELETE FROM TIPOS_CULTURA WHERE idTipoCultura = ?;
DELETE FROM UNIDADES_MEDIDA WHERE idUnidadeMedida = ?;
