@startuml

title Domain Model Agricultural exploration

left to right direction

skinparam classAttributeIconSize 0
hide circle
hide methods

class Quinta{
    nome
    morada
}

abstract class Utilizador{
    nome
}

class Funcionário extends Utilizador{
    função
}

class Cliente extends Utilizador{
}

class Edíficios{
}

class Armazém extends Edíficios{
    area
}

class Estábulo extends Edíficios{
    area
}

class Garagem extends Edíficios{
    area
}

class SistemaDeRega extends Edíficios{
    area
}

class Parcelas{
    desegnação
    area
    cultura
}

class FatoresDeProdução{
}

class Cultura {
}

class Produtos{}

class Animais extends Produtos{}

class Vegetais extends Produtos {}

Quinta "1" -- "0.*" Parcelas : tem
Quinta "1" -- "0.*" Edíficios : tem
FatoresDeProdução "0.*" -- "0.*" Parcelas : é aplicado em
Funcionário "1" -- "0.*" Cultura : Gestor agrícula gere
Cultura "0.*" -- "0.*" Parcelas : cultivado em
Vegetais "0.*" -- "0.*" Parcelas : produzido em
Cliente "1" -- "0.*" Produtos : compra
Funcionário "1" -- "0.*" Produtos : Motorista : recolhe e distribui
Animais "0.*" -- "1" Estábulo : habita


@enduml